### ISSUE TITLE
preferredCitation

### ISSUE THREAD

**Issue by shnizzedy** [ReproNim/reproschema#135]
For any arbitrary entity, we should have a way to specify a literal preferred citation.

@satra, I know you [said](https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/94#issuecomment-468071770) you

> wanted to stick to things in schema.org if possible

but I think [http://id.loc.gov/ontologies/bibframe/preferredCitation](http://id.loc.gov/ontologies/bibframe.html#p_preferredCitation) might be the way to go on this issue

**Comment by satra** [comment]
@shnizzedy - sounds good.

@sanuann - can you add this to the validator and to an example (like the phq9)?

**Comment by satra** [comment]
@shnizzedy - is there a reason why we shouldn't use the basic:

https://schema.org/citation

**Comment by shnizzedy** [comment]
I'm talking here about encoding a preferred way to cite the entity with the property:

```ttl
<subject> bibframe:preferredCitation "literal citation text and formatting"
```

`schema:citation` is for citing one creative work from another:

```ttl
<subject> schema:citation <citedWork>
```

I think we probably _should_ use `schema:citation`, but not for this use case.

**Comment by satra** [comment]
schema.org also allows "text"

**Comment by shnizzedy** [comment]
Sure, but what I'm asking for here is a place to define a preferred citation for a thing itself, not for citing something else. The definition of `schema:citation` includes the word 'another' _twice_!

**Comment by satra** [comment]
i completely agree that `schema.org/citation` is not very well defined, but i think it is intended to serve the same purpose.

to work through two examples:

1. the PHQ-9 is a published form: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1495268/

so the PHQ9 activity would have as property:

schema:citation "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1495268/"

2. now for a custom activity or activity set like those in our voice pilot, the only citation would be their URL, because they are not referencing any other work.

how this should be cited is an open question. at one level, someone could create a custom project somewhere on github and publish it on zenodo. and then the citation for that project would be the zenodo doi. i do think studies should have their own projects and hence versioned releases. they can register this through a server or we create a separate github organization to house these (similar to conda forge or niflows).

**Comment by shnizzedy** [comment]
Ah, I see what you're saying. We just use `citation` where there's an external citation, and we use the applet's metadata otherwise. In that case, we should probably include some authorship and agent-of-responsibility metadata so the citations don't assume the person who encoded the entity authored the entity.

**Comment by satra** [comment]
@shnizzedy - this is why i almost want every activity/sctivityset to get dois via zenodo and a citation that includes different contributors acknowledged. i did get reprosets, but we should have a call to brainstorm workflow and organization.
