### ISSUE TITLE
host the master branch of this repo on github pages 

### ISSUE THREAD

**Issue by akeshavan** [ReproNim/reproschema#183]
If we host the master branch of this repo on github pages, things will load faster, and I think the cache will refresh faster, too! @satra @sanuann can you change the setting?

**Comment by satra** [comment]
i've enabled it, but because of repronim this gets served through: http://repronim.org/schema-standardization/ but the links would still go as currently defined. 

also:
1. we are going to use purl to redirect things
2. have reprosets the organization. 
3. i don't think we took a decision on what to name the "thing"

once sanu is done with the audio widget and backend server, we can focus on cleaning up the jsonld, finishing the validator, and then using proper web servers.

is the speed a real bottleneck right now?

**Comment by akeshavan** [comment]
kind of -- editing the jsonld's on a slow cache is a pain!

**Comment by satra** [comment]
thanks @akeshavan - let's all brainstorm how best to store, retrieve, edit, and track changes on the jsonld files - there may be other means to do this. we don't have to use github, but it's a nice backend that takes care of a few things.
