### ISSUE TITLE
input types questions

### ISSUE THREAD

**Issue by akeshavan** [ReproNim/reproschema#39]
I took a look at all ui.inputType entries in all the jsonld files in the items/*

```python
{'',
 'date',
 'multiple choice',
 'number',
 'radio',
 'single choice, text entry',
 'slider',
 'text',
 'text entry. ',
 'xsd:int'}
```

A few questions:
1) what is `multiple choice`, is that the same as a radio? or checkboxes?
2) `single choice, text entry`, is that the same as `text`?
3) same for `'text entry.'`
4) `xsd:int` is an integer, and `number` can be any number?

Can we add an item for `audioRecord`?

**Comment by sanuann** [comment]
1, 3 - yes. i will resolve it tomorrow morning.
2 - some questions have a radio button for answer choices plus a text field for "don't know"
4 - i have to check

**Comment by akeshavan** [comment]
I think we should specify in the schema whether we want a "skip" option and a "don't know" option. Also I think don't know should be a checkbox. I'm not sure why it's a text field on Mindlogger.

**Comment by shnizzedy** [comment]
Related https://github.com/ChildMindInstitute/mindlogger-app-backend/issues/33

I strongly think 0‒many non-response options should be user-defined. For example, "skip", "don't know", and "not applicable" and other non-response options could all be relevant, valid, and differentially informative responses to a question, and an Editor may or may not want to allow Users to choose among some subset of these responses.

> 2. `single choice, text entry`, is that the same as `text`?

> 2 - some questions have a radio button for answer choices plus a text field for "don't know"

> I'm not sure why it's a text field on Mindlogger

I don't know why a "Don't Know" would be a text field paired with radio buttons, but I do know we have some assessments that have an input type other than checkbox/radio ("Survey List" as it's called in the panel) and that a text box for "Don't Know" is our current hack to get around this shortcoming. That we can append a (single) text box but not any other kind of input to a screen with another entry type is a deficiency in the interface (both in the app and the panel), not a feature to force into the data schema.

Mindlogger is an infant and in constant flux; this schema repository is structured much better. We should fix the interface to match our requirements, not the other way around.

**Comment by sanuann** [comment]
> I think we should specify in the schema whether we want a "skip" option and a "don't know" option. Also I think don't know should be a checkbox. I'm not sure why it's a text field on Mindlogger.

there is a key "requiredValue" in the valueConstraints.jsonld which denotes if it can be skipped or not. perhaps we can rename the key to "skippable" and move it from valueConstraints to the item schema (eg. to phq9_1.jsonld)?

**Comment by sanuann** [comment]
@zaliqarosli you may list other types here if you can.

**Comment by zaliqarosli** [comment]
> 2 - some questions have a radio button for answer choices plus a text field for "don't know"

We also need this in LORIS but we call this collection of two input elements a "group". (For document sake) In yesterday's call, we suggested that "dontknow" type answers should be its own field item with inputType: whatever we choose, e.g. checkbox or button. 

> there is a key "requiredValue" in the valueConstraints.jsonld which denotes if it can be skipped or not. perhaps we can rename the key to "skippable" and move it from valueConstraints to the item schema (eg. to phq9_1.jsonld)?

required fields work a little differently in loris. if the field is not required, it is skippable. if the field is required, it is part of a group with a "not_answered" or "dont_know" option so that an intentional non-answering is submitted. (we can't make people answer a question they don't have an answer to). I would suggest bringing "requireIf" to the activity level as a field's "required" can be dependent on the answer to another field.

> @zaliqarosli you may list other types here if you can.

assuming inputType is only the front-end element type the field will be rendered as, these are the LORIS types: 
- checkbox, date, number, radio, select, text, textarea, time, slider
- (technically non-input) header, link, static
